### ISSUE TITLE
rename scrypt-ts to sCrypt

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/woc-scrypt-verifier-plugin#1]
Update the diagram at https://scrypt.io/scrypt-ts/how-to-verify-a-contract afterwards.
![image](https://user-images.githubusercontent.com/1017252/223217086-a9fd5126-20e7-4ed1-9ad2-b25ca56ae1f2.png)

**Comment by xhliu** [comment]
@msinkec

**Comment by msinkec** [comment]
Docs update: https://github.com/sCrypt-Inc/scryptTS-docs/commit/f5ca5e1402c26c8d8f4370dbda0929e5c75e4f97
