### ISSUE TITLE
Something went wrong when building the smart contract

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/woc-scrypt-verifier-plugin#4]
Reported at https://discord.com/channels/953808129043333140/954737352713064518/1146886430044471376

<img width="1051" alt="image" src="https://github.com/sCrypt-Inc/woc-scrypt-verifier-plugin/assets/1017252/2c733a41-dde6-4554-b59a-fff49defc797">

**Comment by msinkec** [comment]
Plugin was not supporting new project layout. Updated it in 0c3138cbf13b6210cfbae69c4923d655f3999345. Now can use `scrypt-ts` versions >= 1.3
